<?php
/**
 * @file Contains hooks and logic for the visualizer.
 */

/**
 * Implements hook_menu().
 */
function entity_dependency_visualizer_menu() {

  $items['node/%node/entity_dependency_visualizer'] = array(
    'title' => 'Dependencies Graph',
    'page callback' => 'entity_dependency_visualizer_callback',
    'page arguments' => array('node', 1),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 50,
  );
  $items['user/%user/entity_dependency_visualizer'] = array(
    'title' => 'View Graph',
    'page callback' => 'entity_dependency_visualizer_callback',
    'page arguments' => array('user', 1),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 50,
  );
  $items['taxonomy/term/%taxonomy_term/entity_dependency_visualizer'] = array(
    'title' => 'View Graph',
    'page callback' => 'entity_dependency_visualizer_callback',
    'page arguments' => array('taxonomy_term', 2, 'term'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 50,
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function entity_dependency_visualizer_admin_paths() {
  $paths = array(
    'node/*/entity_dependency_visualizer' => TRUE,
    'node/*/entity_dependency_visualizer/*' => TRUE,
    'user/*/entity_dependency_visualizer' => TRUE,
    'user/*/entity_dependency_visualizer/*' => TRUE,
    'taxonomy/term/*/entity_dependency_visualizer' => TRUE,
    'taxonomy/term/*/entity_dependency_visualizer/*' => TRUE,
  );

  return $paths;
}

/**
 * Callback for menu items.
 */
function entity_dependency_visualizer_callback($type, $object, $name = NULL) {

  switch ($type) {
    case 'node':
      if (!user_access('edit own ' . $object->type . ' content') && !user_access('edit any ' . $object->type . ' content')) {
        drupal_access_denied();
      }
      $id = $object->nid;
      break;

    case 'taxonomy_term':
      if (!user_access('edit terms in ' . $object->vid)) {
        drupal_access_denied();
      }
      $id = $object->tid;
      break;

    case 'user':
      if (!user_access('access user profiles')) {
        drupal_access_denied();
      }
      $id = $object->uid;
      break;

    default:
      drupal_set_message(t('Entity type %t is not supported by Entity Dependency Visualizer.', array('%t' => $type)), 'error');
      return;
  }

  $entities = array(
    array(
      'type' => $type,
      'id' => $id
    )
  );

  $result = entity_dependency_visualizer_get_list($entities);
  $data = entity_dependency_visualizer_get_graphviz($result);

  // Add scripts.
  $settings_js = array(
    'entity_dependency_visualizer' => array(
      'data' => $data,
    ),
  );
  drupal_add_js($settings_js, 'setting');
  drupal_add_js('http://webgraphviz.com/viz.js', 'external');
  drupal_add_js(drupal_get_path('module', 'entity_dependency_visualizer') . '/js/entity_dependency_visualizer.js');

  $html = '';
  if (variable_get('entity_dependency_visualizer_display_data', TRUE)) {
    $html = '<textarea id="graphviz_data" rows="4" cols="60" style="width: 100%">' . $data . '</textarea>';
  }
  $html .= '<div id="graphviz_svg_div"></div>';

  return $html;
}

/**
 * Process dependencies.
 *
 * @param $entities array
 *   List of entities.
 * @return array
 *   The array of dependencies.
 * @todo
 *   Batch this to support large entities.
 */
function entity_dependency_visualizer_get_list($entities) {
  $iterator = new DeployIterator($entities);
  $dependencies = new EntityDependencyIteratorIterator($iterator);

  $list = [];
  foreach ($dependencies as $entity) {
    $type = NULL;
    $identifier = NULL;

    if (isset($entity->uid) && isset($entity->name) && isset($entity->mail) && isset($entity->pass)) {
      $type = 'user';
      $id = $entity->uid;
    }
    else if (isset($entity->fid) && isset($entity->filename) && isset($entity->filemime) && isset($entity->uri)) {
      $type = 'file';
      $id = $entity->fid;
    }
    else if (isset($entity->nid)) {
      $type = 'node';
      $id = $entity->nid;
    }
    else if (isset($entity->tid)) {
      $type = 'taxonomy_term';
      $id = $entity->tid;
    }
    else if ($entity instanceof FieldCollectionItemEntity) {
      $type = 'field_collection_item';
      $id = $entity->item_id;
    }
    else if ($entity == new stdClass()) {
      // Ignore blank entities that were possibly removed in hook_deploy_deploy_entity_alter().
      continue;
    }
    else {
      drupal_set_message(t('Entity Visualizer error: Unknown entity <pre>%e</pre>', array('%e' => var_export($entity, TRUE))), 'error');
      continue;
    }

    if (empty($entity->uuid)) {
      watchdog('entity_dependency_visualizer', t('Entity is missing UUID <pre>%e</pre>'), array('%e' => var_export($entity, TRUE)), WATCHDOG_ERROR);
      continue;
    }

    $list[$type][$id] = array (
      'id' => $id,
      'type' => $type,
      'uuid' => $entity->uuid,
    );
  }

  return array (
    'causes' => $iterator->causes,
    'keep' => $list,
  );
}

/**
 * Gets the Graphviz object, see Graphviz http://www.webgraphviz.com
 *
 * @param $list
 *    The list of objects
 * @return string
 *    The Graphviz object.
 */
function entity_dependency_visualizer_get_graphviz($list) {
  // @todo Make this configurable.
  $definitions = array(
    'size' => '30,30',
    'graph' => array (
      'style' => 'filled',
      'fontname' => 'Arial',
      'fontsize' => '40',
      'style' => 'bold',
      'label' => t('Dependencies tree'),
      'ssize' => '30,60',
    ),
    'node' => array (
      'style' => 'filled',
      'fontname' => 'Verdana',
      'shape' => 'circle',
      'size' => '8,8',
    ),
  );

  $graph_obj = 'digraph sdsu {';
  foreach ($definitions as $key => $definition) {
    if (is_array($definition)) {
      $graph_obj .=  "\t" . $key . ' [';
      foreach ($definition as $dk => $item) {
        $graph_obj .= $dk . '="' . $item . '"';
      }
      $graph_obj .= '];' . PHP_EOL;
    }
    else {
      $graph_obj .= $key . '="' . $definition . '";' . PHP_EOL;
    }
  }

  $i = 0;
  $keep = $list['keep'];
  $causes = $list['causes'];
  foreach ($causes as $type => $items) {
    foreach ($items as $id => $item) {
      if (!is_array($item)) {
        continue;
      }
      $to = $type . '\n' . $id;
      $from = '';
      if (isset($item['type'])) {
        $from = $item['type'];
      }
      if (isset($item['id'])) {
        $from .= '\n' . $item['id'];
      }
      $i++;
      $label = '#' . $i . '\n';

      switch ($type) {
        case 'node':
          $color = 'coral';
          break;

        case 'taxonomy_term':
          $color = 'greenyellow';
          break;

        case 'field_collection_item':
          $color = 'deepskyblue';
          break;

        case 'file':
          $color = 'gold';
          break;

        case 'user':
          $color = 'deeppink1';
          break;

        default:
          $label = '(' . $type . ')\n' . $label;
          $color = 'gray81';
      }
      if (!isset($keep[$type][$id])) {
        if (variable_get('entity_dependency_visualizer_display_removed', FALSE)) {
          // Do not display removed dependencies.
          continue;
        }
        $color = 'ghostwhite';
      }

      $graph_obj .= '"' . $to . '" [color="' . $color . '"];' . PHP_EOL;
      $graph_obj .= '"' . $from . '" -> "' . $to . '" [ label = "' . $label . '" ];' . PHP_EOL;
    }
  }
  $graph_obj .= '}';

  return $graph_obj;
}
