entity_dependency_visualizer.settings:
  type: config_object
  label: 'Entity Dependency Visualizer settings'
  mapping:
    dependency_calculator_plugin:
      type: string
      label: 'The plugin used for dependencies calculations'
    show_graphviz_object:
      type: boolean
      label: 'Display graphviz object on the top of the page'
    ellipsis:
      type: boolean
      label: 'Limit the size of labels and add ... at the end'
    ignore_fields:
      type: sequence
      label: 'Ignore fields'
      orderby: key
      sequence:
        type: string
        label: 'Field to be ignored i.e. node:field_name'
    graph:
      type: entity_dependency_visualizer.[%key]

entity_dependency_visualizer.graph:
  type: mapping
  label: 'Graph settings'
  mapping:
    size:
      type: string
      label: 'Graph size'
    ratio:
      type: string
      label: 'Graph ratio'
    rankdir:
      type: string
      label: 'Direction i.e. LR or TB'
    graph:
      type: entity_dependency_visualizer.graph.[%key]
    arrows:
      type: entity_dependency_visualizer.graph.[%key]
    node:
      type: entity_dependency_visualizer.graph.[%key]

entity_dependency_visualizer.graph.graph:
  type: mapping
  label: 'Graph settings'
  mapping:
    label:
      type: string
      label: 'The graph label'
    style:
      type: string
      label: 'The graph style'
    fontstyle:
      type: string
      label: 'The font style'
    fontname:
      type: string
      label: 'The font name'
    ssize:
      type: string
      label: 'The ssize'
    fontsize:
      type: integer
      label: 'Label font size'

entity_dependency_visualizer.graph.arrows:
  type: mapping
  label: 'Arrows settings and label'
  mapping:
    display_order:
      type: boolean
      label: 'Display order number in the label'
    display_content_type:
      type: boolean
      label: 'Display content type in the label'
    display_field_name:
      type: boolean
      label: 'Display field name in the label'
    display_entity_id:
      type: boolean
      label: 'Display entity Id in the label'
    fontsize:
      type: integer
      label: 'Label font size'

entity_dependency_visualizer.graph.node:
  type: mapping
  label: 'Node settings'
  mapping:
    shape:
      type: string
      label: 'Node shape'
    display_content_type:
      type: boolean
      label: 'Display content type in the label'
    style:
      type: string
      label: 'The graph style'
    fontstyle:
      type: string
      label: 'The font style'
    fontname:
      type: string
      label: 'The font name'
    fontsize:
      type: integer
      label: 'Label font size'
    caption:
      type: string
      label: 'Caption to display inside the shape'